package blargh.warhammer.android;

public class DbStatments {

	static final String[] createStatements = new String[]{
		"create table if not exists person(uid integer primary key autoincrement, name text);", 
		"create table if not exists spec(spec text primary key);", 
		"create table if not exists stat(stat text primary key);", 
		"create table if not exists skill(skill text primary key, spec boolean, stat references stat(stat));", 
		"create table if not exists skills(person_uid references person(uid), skill references skill(skill), spec references spec(spec), training integer);", 
		"create table if not exists skill_spec(skill references skill(skill), spec references spec(spec));", 
		"create table if not exists talent(talent text primary key, spec boolean);", 
		"create table if not exists talents(person_uid references person(uid), talent references talent(talent), spec references spec(spec));", 
		"create table if not exists talent_spec(talent references talent(talent), spec references spec(spec));", 
		"create table if not exists trait(trait text primary key);", 
		"create table if not exists traits(person_uid references person(uid), talent references talent(talent), value integer);", 
		"create table if not exists weapon_special(special text);", 
		"create table if not exists ranged_weapon(name text, class references ranged_class(class), range text, single_shot boolean, semi_auto integer, full_auto integer, damage_dice integer, damage_modifier integer, damage_type references damage(type), penetration integer, clip integer, reload integer, weight integer);", 
		"create table if not exists ranged_specials (ranged_name references ranged_weapon(name), special references weapon_special(special));", 
		"create table if not exists melee_weapon(name text, class references melee_class(class), damage_dice integer, damage_modifier integer, damage_type references damage(type), penetration integer, weight integer);", 
		"create table if not exists melee_specials (melee_name references melee_weapon(name), special references weapon_special(special));", 
		"create table if not exists armor(name text, head integer, arms integer, body integer, legs integer, weight integer);"
	};

	static final String[] destroyStatements = new String[]{
		"drop table if exists person;", 
		"drop table if exists skill;", 
		"drop table if exists skills;", 
		"drop table if exists skill_spec;", 
		"drop table if exists talents;", 
		"drop table if exists talent;", 
		"drop table if exists talent_spec;", 
		"drop table if exists traits;", 
		"drop table if exists trait;", 
		"drop table if exists spec;", 
		"drop table if exists ranged_weapon;", 
		"drop table if exists ranged_specials;", 
		"drop table if exists melee_weapon;", 
		"drop table if exists melee_specials;", 
		"drop table if exists weapon_special;", 
		"drop table if exists armor;"
	};

	static final String[] talentsStatements = new String[]{
		"insert into talent(talent) values ('Abhor the Witch)');",
		"insert into talent(talent) values ('Acolyte Network)');",
		"insert into talent(talent) values ('Air of Authority)');",
		"insert into talent(talent) values ('Ally of the Departmento Munitorum)');",
		"insert into talent(talent) values ('Ambidextrous)');",
		"insert into talent(talent) values ('Armour of Contempt)');",
		"insert into talent(talent) values ('Armour-monger)');",
		"insert into talent(talent) values ('Arms Master)');",
		"insert into talent(talent) values ('Ascended Psychic Power)');",
		"insert into talent(talent) values ('Assassin Strike)');",
		"insert into talent(talent) values ('Astartes Weapon Specialization)');",
		"insert into talent(talent) values ('Astartes Weapon Training)');",
		"insert into talent(talent) values ('Autosanguine)');",
		"insert into talent(talent) values ('Basic Weapons Expertise)');",
		"insert into talent(talent) values ('Basic Weapon Training(bolt)');",
		"insert into talent(talent) values ('Basic Weapon Training(flame)');",
		"insert into talent(talent) values ('Basic Weapon Training(las)');",
		"insert into talent(talent) values ('Basic Weapon Training(launcher)');",
		"insert into talent(talent) values ('Basic Weapon Training(melta)');",
		"insert into talent(talent) values ('Basic Weapon Training(plasma)');",
		"insert into talent(talent) values ('Basic Weapon Training(primitive)');",
		"insert into talent(talent) values ('Basic Weapon Training(sp)');",
		"insert into talent(talent) values ('Basic Weapon Training(universal)');",
		"insert into talent(talent) values ('Bastion of Iron Will)');",
		"insert into talent(talent) values ('Battle Rage)');",
		"insert into talent(talent) values ('Berserk Charge)');",
		"insert into talent(talent) values ('Berserker)');",
		"insert into talent(talent) values ('Binary Chatter)');",
		"insert into talent(talent) values ('Blade Dancer)');",
		"insert into talent(talent) values ('Blademaster)');",
		"insert into talent(talent) values ('Blessed Radiance)');",
		"insert into talent(talent) values ('Blind Fighting)');",
		"insert into talent(talent) values ('Bloodtracker)');",
		"insert into talent(talent) values ('Bolter Drill)');",
		"insert into talent(talent) values ('Bulging Biceps)');",
		"insert into talent(talent) values ('Call of Iron)');",
		"insert into talent(talent) values ('Call To Vengeance)');",
		"insert into talent(talent) values ('Catfall)');",
		"insert into talent(talent) values ('Chem Geld)');",
		"insert into talent(talent) values ('Cleanse and Purify)');",
		"insert into talent(talent) values ('Combat Formation)');",
		"insert into talent(talent) values ('Combat Master)');",
		"insert into talent(talent) values ('Combat Sense)');",
		"insert into talent(talent) values ('Committed Xanthite)');",
		"insert into talent(talent) values ('Concealed Cavity)');",
		"insert into talent(talent) values ('Conciliator)');",
		"insert into talent(talent) values ('Conditioned Intellect)');",
		"insert into talent(talent) values ('Corpus Conversion)');",
		"insert into talent(talent) values ('Counter-attack)');",
		"insert into talent(talent) values ('Crack Shot)');",
		"insert into talent(talent) values ('Crimelord)');",
		"insert into talent(talent) values ('Crippling Strike)');",
		"insert into talent(talent) values ('Crushing Blow)');",
		"insert into talent(talent) values ('Dark Soul)');",
		"insert into talent(talent) values ('Deadeye Shot)');",
		"insert into talent(talent) values ('Death Blow)');",
		"insert into talent(talent) values ('Death From Above)');",
		"insert into talent(talent) values ('Deathwatch Training)');",
		"insert into talent(talent) values ('Decadence)');",
		"insert into talent(talent) values ('Deflect Shot)');",
		"insert into talent(talent) values ('Denouncer)');",
		"insert into talent(talent) values ('Die Hard)');",
		"insert into talent(talent) values ('Disarm)');",
		"insert into talent(talent) values ('Discipline Focus(biomancy)');",
		"insert into talent(talent) values ('Discipline Focus(divination)');",
		"insert into talent(talent) values ('Discipline Focus(pyromancy)');",
		"insert into talent(talent) values ('Discipline Focus(telekinetics)');",
		"insert into talent(talent) values ('Discipline Focus(telepathy)');",
		"insert into talent(talent) values ('Disturbing Voice)');",
		"insert into talent(talent) values ('Divine Ministration)');",
		"insert into talent(talent) values ('Double Team)');",
		"insert into talent(talent) values ('Dual Shot)');",
		"insert into talent(talent) values ('Dual Strike)');",
		"insert into talent(talent) values ('Duty Unto Death)');",
		"insert into talent(talent) values ('Electrical Succour)');",
		"insert into talent(talent) values ('Electro Graft Use)');",
		"insert into talent(talent) values ('Electro Illumination)');",
		"insert into talent(talent) values ('Enemy(specific)');",
		"insert into talent(talent) values ('Energy Cache)');",
		"insert into talent(talent) values ('Enhanced Bionic Frame)');",
		"insert into talent(talent) values ('Exemplar of Honour)');",
		"insert into talent(talent) values ('Exemplar of Metal)');",
		"insert into talent(talent) values ('Exotic Weapon Training(specific)');",
		"insert into talent(talent) values ('Eye of Vengeance)');",
		"insert into talent(talent) values ('Favoured By Fate)');",
		"insert into talent(talent) values ('Favoured By the Warp)');",
		"insert into talent(talent) values ('Fearless)');",
		"insert into talent(talent) values ('Feedback Screech)');",
		"insert into talent(talent) values ('Ferric Lure)');",
		"insert into talent(talent) values ('Ferric Summons)');",
		"insert into talent(talent) values ('Flagellant)');",
		"insert into talent(talent) values ('Flame Weapon Training(universal)');",
		"insert into talent(talent) values ('Flesh Render)');",
		"insert into talent(talent) values ('Foresight)');",
		"insert into talent(talent) values ('Frenzy)');",
		"insert into talent(talent) values ('Furious Assault)');",
		"insert into talent(talent) values ('Good Reputation(specific)');",
		"insert into talent(talent) values ('Gravitic Levitation)');",
		"insert into talent(talent) values ('Guardian)');",
		"insert into talent(talent) values ('Gun Blessing)');",
		"insert into talent(talent) values ('Gunfighter Saint)');",
		"insert into talent(talent) values ('Gunslinger)');",
		"insert into talent(talent) values ('Hammer Blow)');",
		"insert into talent(talent) values ('Hard Bargain)');",
		"insert into talent(talent) values ('Hard Target)');",
		"insert into talent(talent) values ('Hardy)');",
		"insert into talent(talent) values ('Hatred(chaos Space Marines)');",
		"insert into talent(talent) values ('Hatred(criminals)');",
		"insert into talent(talent) values ('Hatred(cult(specific)');",
		"insert into talent(talent) values ('Hatred(daemons)');",
		"insert into talent(talent) values ('Hatred(heretics)');",
		"insert into talent(talent) values ('Hatred(mutants)');",
		"insert into talent(talent) values ('Hatred(rogue Trader(specific)');",
		"insert into talent(talent) values ('Hatred(pirates)');",
		"insert into talent(talent) values ('Hatred(psykers)');",
		"insert into talent(talent) values ('Hatred(xeno(specific)');",
		"insert into talent(talent) values ('Heavy Weapon Training(bolt)');",
		"insert into talent(talent) values ('Heavy Weapon Training(flame)');",
		"insert into talent(talent) values ('Heavy Weapon Training(las)');",
		"insert into talent(talent) values ('Heavy Weapon Training(launcher)');",
		"insert into talent(talent) values ('Heavy Weapon Training(melta)');",
		"insert into talent(talent) values ('Heavy Weapon Training(plasma)');",
		"insert into talent(talent) values ('Heavy Weapon Training(primitive)');",
		"insert into talent(talent) values ('Heavy Weapon Training(sp)');",
		"insert into talent(talent) values ('Heavy Weapon Training(universal)');",
		"insert into talent(talent) values ('Heavy Weapons Expertise)');",
		"insert into talent(talent) values ('Heightened Reactions)');",
		"insert into talent(talent) values ('Heightened Senses(sight)');",
		"insert into talent(talent) values ('Heightened Senses(sound)');",
		"insert into talent(talent) values ('Heightened Senses(smell)');",
		"insert into talent(talent) values ('Heightened Senses(taste)');",
		"insert into talent(talent) values ('Heightened Senses(touch)');",
		"insert into talent(talent) values ('Hidden Cultist)');",
		"insert into talent(talent) values ('Hip Shooting)');",
		"insert into talent(talent) values ('Hotshot Pilot)');",
		"insert into talent(talent) values ('Hunter of Aliens)');",
		"insert into talent(talent) values ('Improved Warp Sense)');",
		"insert into talent(talent) values ('Independent Targeting)');",
		"insert into talent(talent) values ('Indomitable Fortitude)');",
		"insert into talent(talent) values ('Infused Knowledge)');",
		"insert into talent(talent) values ('Insanely Faithful)');",
		"insert into talent(talent) values ('Inspire Wrath)');",
		"insert into talent(talent) values ('Into the Jaws of Hell)');",
		"insert into talent(talent) values ('Iron Discipline)');",
		"insert into talent(talent) values ('Iron Jaw)');",
		"insert into talent(talent) values ('Jaded)');",
		"insert into talent(talent) values ('Killing Strike)');",
		"insert into talent(talent) values ('Leap Up)');",
		"insert into talent(talent) values ('Last Man Standing)');",
		"insert into talent(talent) values ('Light Sleeper)');",
		"insert into talent(talent) values ('Lightning Attack)');",
		"insert into talent(talent) values ('Lightning Reflexes)');",
		"insert into talent(talent) values ('Litany of Hate)');",
		"insert into talent(talent) values ('Logis Implant)');",
		"insert into talent(talent) values ('Lord of Domains)');",
		"insert into talent(talent) values ('Luminen Blast)');",
		"insert into talent(talent) values ('Luminen Charge)');",
		"insert into talent(talent) values ('Luminen Shock)');",
		"insert into talent(talent) values ('Machinator Array)');",
		"insert into talent(talent) values ('Machine Spirit Empathy)');",
		"insert into talent(talent) values ('Maglev Grace)');",
		"insert into talent(talent) values ('Maglev Transcendence)');",
		"insert into talent(talent) values ('Marksman)');",
		"insert into talent(talent) values ('Master&commander)');",
		"insert into talent(talent) values ('Master Chirurgeon)');",
		"insert into talent(talent) values ('Master Enginseer)');",
		"insert into talent(talent) values ('Master Orator)');",
		"insert into talent(talent) values ('Mechadendrite Use(gun)');",
		"insert into talent(talent) values ('Mechadendrite Use(machine Spirit Interface)');",
		"insert into talent(talent) values ('Mechadendrite Use(manipulator)');",
		"insert into talent(talent) values ('Mechadendrite Use(medicae)');",
		"insert into talent(talent) values ('Mechadendrite Use(optical)');",
		"insert into talent(talent) values ('Mechadendrite Use(servo-arm)');",
		"insert into talent(talent) values ('Mechadendrite Use(utility)');",
		"insert into talent(talent) values ('Mechadendrite Use(weapon)');",
		"insert into talent(talent) values ('Meditation)');",
		"insert into talent(talent) values ('Melee Weapon Expertise)');",
		"insert into talent(talent) values ('Melee Weapon Training(primitive)');",
		"insert into talent(talent) values ('Melee Weapon Training(chain)');",
		"insert into talent(talent) values ('Melee Weapon Training(shock)');",
		"insert into talent(talent) values ('Melee Weapon Training(power)');",
		"insert into talent(talent) values ('Melee Weapon Training(universal)');",
		"insert into talent(talent) values ('Member of the Tyrantine Cabal)');",
		"insert into talent(talent) values ('Mental Aegis)');",
		"insert into talent(talent) values ('Mental Fortress)');",
		"insert into talent(talent) values ('Mental Rage)');",
		"insert into talent(talent) values ('Mighty Shot)');",
		"insert into talent(talent) values ('Mimic)');",
		"insert into talent(talent) values ('Minor Psychic Power(specific)');",
		"insert into talent(talent) values ('Mnemonic Purging)');",
		"insert into talent(talent) values ('Navigator)');",
		"insert into talent(talent) values ('Navigator Power)');",
		"insert into talent(talent) values ('Nerves of Steel)');",
		"insert into talent(talent) values ('Oath Bonded To the Angels of Death)');",
		"insert into talent(talent) values ('Orthoproxy)');",
		"insert into talent(talent) values ('Outspoken Monodominant)');",
		"insert into talent(talent) values ('Paranoia)');",
		"insert into talent(talent) values ('Peer(specific)');",
		"insert into talent(talent) values ('Peerless Marksman)');",
		"insert into talent(talent) values ('Perfect Shot)');",
		"insert into talent(talent) values ('Pious Observation)');",
		"insert into talent(talent) values ('Pistol Expertise)');",
		"insert into talent(talent) values ('Pistol Training(bolt)');",
		"insert into talent(talent) values ('Pistol Training(flame)');",
		"insert into talent(talent) values ('Pistol Training(las)');",
		"insert into talent(talent) values ('Pistol Training(launcher)');",
		"insert into talent(talent) values ('Pistol Training(melta)');",
		"insert into talent(talent) values ('Pistol Training(plasma)');",
		"insert into talent(talent) values ('Pistol Training(primitive)');",
		"insert into talent(talent) values ('Pistol Training(sp)');",
		"insert into talent(talent) values ('Pistol Training(universal)');",
		"insert into talent(talent) values ('Polyglot)');",
		"insert into talent(talent) values ('Power Well)');",
		"insert into talent(talent) values ('Precise Blow)');",
		"insert into talent(talent) values ('Preternatural Speed)');",
		"insert into talent(talent) values ('Prosanguine)');",
		"insert into talent(talent) values ('Psy Rating)');",
		"insert into talent(talent) values ('Psychic Discipline)');",
		"insert into talent(talent) values ('Psychic Power(specific)');",
		"insert into talent(talent) values ('Psychic Technique(specific)');",
		"insert into talent(talent) values ('Pure Faith)');",
		"insert into talent(talent) values ('Purge the Unclean)');",
		"insert into talent(talent) values ('Purity of the Machine)');",
		"insert into talent(talent) values ('Quick Draw)');",
		"insert into talent(talent) values ('Rapid Reaction)');",
		"insert into talent(talent) values ('Rapid Reload)');",
		"insert into talent(talent) values ('Renowned Warrant)');",
		"insert into talent(talent) values ('Renowned Warrior)');",
		"insert into talent(talent) values ('Resistance(cold)');",
		"insert into talent(talent) values ('Resistance(fear)');",
		"insert into talent(talent) values ('Resistance(heat)');",
		"insert into talent(talent) values ('Resistance(poisons)');",
		"insert into talent(talent) values ('Resistance(psychic Powers)');",
		"insert into talent(talent) values ('Revolutionary)');",
		"insert into talent(talent) values ('Rite of Awe)');",
		"insert into talent(talent) values ('Rite of Fear)');",
		"insert into talent(talent) values ('Rite of Protection)');",
		"insert into talent(talent) values ('Rite of Pure Thought)');",
		"insert into talent(talent) values ('Rite of Sanctioning)');",
		"insert into talent(talent) values ('Rival(specific)');",
		"insert into talent(talent) values ('Scourge of Heretics)');",
		"insert into talent(talent) values ('Servo-harness Integration)');",
		"insert into talent(talent) values ('Shadowlord)');",
		"insert into talent(talent) values ('Sharpshooter)');",
		"insert into talent(talent) values ('Signature Wargear)');",
		"insert into talent(talent) values ('Signature Wargear(master)');",
		"insert into talent(talent) values ('Signature Wargear(hero)');",
		"insert into talent(talent) values ('Slayer of Daemons)');",
		"insert into talent(talent) values ('Sleeper Agent)');",
		"insert into talent(talent) values ('Soul of Stone)');",
		"insert into talent(talent) values ('Sound Constitution)');",
		"insert into talent(talent) values ('Sprint)');",
		"insert into talent(talent) values ('Stalwart Defence)');",
		"insert into talent(talent) values ('Step Aside)');",
		"insert into talent(talent) values ('Storm of Blows)');",
		"insert into talent(talent) values ('Storm of Iron)');",
		"insert into talent(talent) values ('Street Fighting)');",
		"insert into talent(talent) values ('Strong Minded)');",
		"insert into talent(talent) values ('Sure Strike)');",
		"insert into talent(talent) values ('Swift Attack)');",
		"insert into talent(talent) values ('Takedown)');",
		"insert into talent(talent) values ('Talented(specific)');",
		"insert into talent(talent) values ('Target Selection)');",
		"insert into talent(talent) values ('Technical Knock)');",
		"insert into talent(talent) values ('The Ear of the Lord Sector)');",
		"insert into talent(talent) values ('The Emperor Protects)');",
		"insert into talent(talent) values ('The Flesh Is Weak)');",
		"insert into talent(talent) values ('Thrown Weapon Expertise)');",
		"insert into talent(talent) values ('Thrown Weapon Training(chain)');",
		"insert into talent(talent) values ('Thrown Weapon Training(power)');",
		"insert into talent(talent) values ('Thrown Weapon Training(primitive)');",
		"insert into talent(talent) values ('Thrown Weapon Training(shock)');",
		"insert into talent(talent) values ('Thrown Weapon Training(universal)');",
		"insert into talent(talent) values ('Thunder Charge)');",
		"insert into talent(talent) values ('Total Recall)');",
		"insert into talent(talent) values ('Transcendent Hate)');",
		"insert into talent(talent) values ('True Grit)');",
		"insert into talent(talent) values ('Two-weapon Wielder(ballistic)');",
		"insert into talent(talent) values ('Two-weapon Wielder(melee)');",
		"insert into talent(talent) values ('Unarmed Ascendant Mastery)');",
		"insert into talent(talent) values ('Unarmed Master)');",
		"insert into talent(talent) values ('Unarmed Warrior)');",
		"insert into talent(talent) values ('Unassailable Grace)');",
		"insert into talent(talent) values ('Unbowed and Unbroken)');",
		"insert into talent(talent) values ('Unremarkable)');",
		"insert into talent(talent) values ('Unshakeable Faith)');",
		"insert into talent(talent) values ('Voice of the Masses)');",
		"insert into talent(talent) values ('Voice of the Omnissiah)');",
		"insert into talent(talent) values ('Void Tactician)');",
		"insert into talent(talent) values ('Wall of Steel)');",
		"insert into talent(talent) values ('Warmonger)');",
		"insert into talent(talent) values ('Warp Affinity)');",
		"insert into talent(talent) values ('Warp Conduit)');",
		"insert into talent(talent) values ('Warp Sense)');",
		"insert into talent(talent) values ('Watched From On High)');",
		"insert into talent(talent) values ('Weapon-tech)');",
		"insert into talent(talent) values ('Whirlwind of Death)');",
		"insert into talent(talent) values ('Whispers)');",
		"insert into talent(talent) values ('Wide Correspondence)');",
		"insert into talent(talent) values ('Wisdom of the Ancients)');",
		"insert into talent(talent) values ('Worthy of the Calixian Elite)');",
		"insert into talent(talent) values ('Wrath of the Righteous)');"
	};

	static final String[] skillsStatements = new String[]{
		"insert into skill(skill, spec, stat) values ('Acrobatics', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Awareness', 'false', 'PER');",
		"insert into skill(skill, spec, stat) values ('Barter', 'false', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Blather', 'true', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Carouse', 'false', 'T');",
		"insert into skill(skill, spec, stat) values ('Charm', 'false', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Chem-use', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(acolyte)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(astropath)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(chapter Runes)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(deathwatch)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(imperial Codes)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(inquisition)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(mercenary Cant)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(nobilite Encoding)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(occult)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(rogue Trader)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(secret Society)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(throne Agent)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(underworld)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(war Cant)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Ciphers(xenos Markings)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Climb', 'false', 'S');",
		"insert into skill(skill, spec, stat) values ('Command', 'false', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Commerce', 'true', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Common Lore(adeptus Arbites)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(adeptus Astartes)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(adeptus Astra Telepathica)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(adeptus Mechanicus)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(administratum)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(deathwatch)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(ecclesiarchy)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(imperial Creed)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(imperial Guard)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(imperial Navy)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(imperium)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(jericho Reach)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(koronus Expanse)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(machine Cult)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(navis Nobilite)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(rogue Traders)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(tech)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(underworld)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Common Lore(war)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Concealment', 'false', 'AG');",
		"insert into skill(skill, spec, stat) values ('Contortionist', 'false', 'AG');",
		"insert into skill(skill, spec, stat) values ('Deceive', 'false', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Demolition', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Disguise', 'false', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Dodge', 'false', 'AG');",
		"insert into skill(skill, spec, stat) values ('Drive(ground Vehicle)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Drive(hover Vehicle)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Drive(walker)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Evaluate', 'false', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(adeptus Astartes)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(adeptus Mechanicus)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(archeotech)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(black Library)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(cults)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(daemonology)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(heresy)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(inquisition)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(mutants)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(navigators)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(officio Assassinorum)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(ordo Hereticus)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(ordo Malleus)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(ordo Xenos)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(pirates)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(psykers)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(traitor Legions)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(warp)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Forbidden Lore(xenos)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Gamble', 'false', 'INT');",
		"insert into skill(skill, spec, stat) values ('Inquiry', 'false', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Interrogation', 'true', 'WP');",
		"insert into skill(skill, spec, stat) values ('Intimidate', 'false', 'S');",
		"insert into skill(skill, spec, stat) values ('Invocation', 'true', 'WP');",
		"insert into skill(skill, spec, stat) values ('Lip Reading', 'true', 'PER');",
		"insert into skill(skill, spec, stat) values ('Literacy', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Logic', 'false', 'INT');",
		"insert into skill(skill, spec, stat) values ('Medicae', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Navigation(stellar)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Navigation(surface)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Navigation(warp)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Performer(dancer)', 'true', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Performer(musician)', 'true', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Performer(singer)', 'true', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Performer(storyteller)', 'true', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Pilot(civilian Craft)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Pilot(flyers)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Pilot(military Craft)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Pilot(personal)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Pilot(spacecraft)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Psyniscience', 'true', 'PER');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(archaic)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(astromancy)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(beasts)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(bureaucracy)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(chymistry)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(codex Astartes)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(cryptology)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(heraldry)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(imperial Creed)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(imperial Warrants)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(judgement)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(legend)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(navis Nobilite)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(numerology)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(occult)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(philosophy)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scholastic Lore(tactica Imperialis)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Scrutiny', 'false', 'PER');",
		"insert into skill(skill, spec, stat) values ('Search', 'false', 'PER');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(acolyte)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(administratum)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(ecclesiarchy)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(gutter)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(military)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(navigator)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(rogue Trader)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(tech)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(throne Agent)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Secret Tongue(underdeck)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Security', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Shadowing', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Silent Move', 'false', 'AG');",
		"insert into skill(skill, spec, stat) values ('Sleight of Hand', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Speak Language(eldar)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(explorator Binary)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(high Gothic)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(hive Dialect)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(kroot)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(low Gothic)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(ork)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(ship Dialect)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(tau)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(techna-lingua)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(traders Cant)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Speak Language(tribal Dialect)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Survival', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Swim', 'false', 'S');",
		"insert into skill(skill, spec, stat) values ('Tactics(air Combat)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tactics(armoured Tactics)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tactics(assault Doctrine)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tactics(defensive Doctrine)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tactics(orbital Drop Procedures)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tactics(recon and Stealth)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tactics(void Combat)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tech-use', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Tracking', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(agri)', 'true', 'S');",
		"insert into skill(skill, spec, stat) values ('Trade(apothecary)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(archaeologist)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(armourer)', 'true', 'S');",
		"insert into skill(skill, spec, stat) values ('Trade(artist)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Trade(astrographer)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Trade(cartographer)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Trade(chymist)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(cook)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(copyist)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(cryptographer)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(embalmer)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(explorator)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(linguist)', 'true', 'INT');",
		"insert into skill(skill, spec, stat) values ('Trade(mason)', 'true', 'AG');",
		"insert into skill(skill, spec, stat) values ('Trade(merchant)', 'true', 'FEL');",
		"insert into skill(skill, spec, stat) values ('Trade(miner)', 'true', 'S');",
		"insert into skill(skill, spec, stat) values ('Trade(prospector)', 'true', 'S');"

	};

	static final String[] statsStatements = new String[]{
		"insert into stat(stat) values ('WS');",
		"insert into stat(stat) values ('BS');",
		"insert into stat(stat) values ('S');",
		"insert into stat(stat) values ('T');",
		"insert into stat(stat) values ('AG');",
		"insert into stat(stat) values ('PER');",
		"insert into stat(stat) values ('INT');",
		"insert into stat(stat) values ('WP');",
		"insert into stat(stat) values ('FEL');"	
	};
}
